# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kajax}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kenji Hara"]
  s.date = %q{2012-03-04}
  s.description = %q{ruby extensions for kick start}
  s.email = %q{hara@mail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "kajax.gemspec",
    "lib/action_controller_extensions.rb",
    "lib/action_controller_extensions/read_params.rb",
    "lib/action_view_extensions.rb",
    "lib/active_record_extensions.rb",
    "lib/active_record_extensions/bulk_insert.rb",
    "lib/active_record_extensions/compare.rb",
    "lib/active_record_extensions/connection.rb",
    "lib/active_record_extensions/conversions.rb",
    "lib/active_record_extensions/count.rb",
    "lib/active_record_extensions/delete.rb",
    "lib/active_record_extensions/insert.rb",
    "lib/active_record_extensions/method_missing.rb",
    "lib/active_record_extensions/query.rb",
    "lib/active_record_extensions/select.rb",
    "lib/active_record_extensions/table.rb",
    "lib/active_record_extensions/update.rb",
    "lib/array_extensions.rb",
    "lib/array_of_hash.rb",
    "lib/cassandra_util.rb",
    "lib/date_extensions.rb",
    "lib/date_util.rb",
    "lib/db_escape.rb",
    "lib/float_extensions.rb",
    "lib/google_data_api.rb",
    "lib/google_data_api/spread_sheet.rb",
    "lib/hadoop_util.rb",
    "lib/hash_extensions.rb",
    "lib/kajax.rb",
    "lib/keyword_alias_util.rb",
    "lib/md5_convert.rb",
    "lib/mq_util.rb",
    "lib/mysql_util.rb",
    "lib/pg_hdfs.rb",
    "lib/pgsql_util.rb",
    "lib/postfix_convert.rb",
    "lib/rspec_util.rb",
    "lib/specific_helper.rb",
    "lib/specific_helper/generate.rb",
    "lib/specific_xml_converter.rb",
    "lib/sql_util.rb",
    "lib/string_extensions.rb",
    "lib/symbol_extensions.rb",
    "lib/twitter_thumbnail_extractor.rb",
    "lib/url_util.rb",
    "spec/kajax_spec.rb",
    "spec/keyword_alias_util_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/haracane/kajax}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.3}
  s.summary = %q{ruby extensions for kick start}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, ["~> 1.0.0"])
      s.add_development_dependency(%q<ci_reporter>, ["~> 1.7.0"])
      s.add_development_dependency(%q<actionpack>, ["~> 3.1.3"])
      s.add_development_dependency(%q<activerecord>, ["~> 3.1.3"])
      s.add_development_dependency(%q<bunny>, [">= 0.7.9"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, ["~> 1.0.0"])
      s.add_dependency(%q<ci_reporter>, ["~> 1.7.0"])
      s.add_dependency(%q<actionpack>, ["~> 3.1.3"])
      s.add_dependency(%q<activerecord>, ["~> 3.1.3"])
      s.add_dependency(%q<bunny>, [">= 0.7.9"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, ["~> 1.0.0"])
    s.add_dependency(%q<ci_reporter>, ["~> 1.7.0"])
    s.add_dependency(%q<actionpack>, ["~> 3.1.3"])
    s.add_dependency(%q<activerecord>, ["~> 3.1.3"])
    s.add_dependency(%q<bunny>, [">= 0.7.9"])
  end
end

